#!/usr/bin/env ruby

require 'optparse'

case ARGV[0]
when 'hugo' then
  exec 'hugo'

when 'serve'
  exec 'hugo serve --navigateToChanged'

when 'build'
  exec 'redo -dxv'

else
  raise "Unrecognized command '#{ARGV[0]}'"

end
