baseURL = ""
languageCode = "en-us"
title = "Dylan Kendal"
publishDir = "docs"
theme = "dkendal"
paginate = 10

[params]
homeTitle = "Dylan Kendal"
description = "A programming blog."
mainSections = "posts"

[author]
name = "Dylan Kendal"

[markup]

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = false
# style = "dracula"
tabWidth = 2

[markup.goldmark]

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.renderer]
unsafe = true

[social]
github = "https://github.com/Dkendal"
linkedin = "https://www.linkedin.com/in/dylan-kendal-24027545/"
