on:
  push:
    branches:
      - update

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with: { version: 'v0.6.17' }

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build docs
        env:
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
        run: |
          earthly --ci --push +docs
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
          git add -Af docs
          git commit -m "Update docs"
          git push -fq origin @:gh-pages
